<script lang="ts">
	import { goto } from '$app/navigation';
	import {
		exportStateToUrl,
		importStateFromUrl,
		estimateUrlSize
	} from '$lib/baseball-lineup-logic.svelte';

	// Props
	let { showModal = $bindable(false), roster = [] }: { showModal?: boolean; roster?: string[] } =
		$props();

	// State
	let shareUrl = $state('');
	let isGeneratingUrl = $state(false);
	let urlSize = $state(0);
	let importUrl = $state('');
	let isImporting = $state(false);
	let importError = $state('');

	// URL sharing functions
	async function generateShareUrl() {
		if (roster.length === 0) {
			alert('Please add at least one player to the roster before sharing.');
			return;
		}

		isGeneratingUrl = true;
		try {
			const urlFragment = await exportStateToUrl();
			shareUrl = `${window.location.origin}${window.location.pathname}${urlFragment}`;
			urlSize = await estimateUrlSize();
		} catch (error) {
			console.error('Failed to generate share URL:', error);
			alert('Failed to generate share URL. Please try again.');
		} finally {
			isGeneratingUrl = false;
		}
	}

	async function copyShareUrl() {
		try {
			await navigator.clipboard.writeText(shareUrl);
			alert('Share URL copied to clipboard!');
		} catch (error) {
			console.error('Failed to copy URL:', error);
			alert('Share URL failed to copy to clipboard!');
		}
	}

	async function importFromUrl() {
		if (!importUrl.trim()) {
			importError = 'Please enter a URL to import from.';
			return;
		}

		isImporting = true;
		importError = '';

		try {
			// Extract hash from URL
			const url = new URL(importUrl);
			const hash = url.hash;

			if (!hash || !hash.startsWith('#v1=')) {
				importError = 'Invalid URL format. Please use a URL generated by this tool.';
				return;
			}

			const success = await importStateFromUrl(hash);
			if (success) {
				alert('Successfully imported lineup data!');
				importUrl = '';
				closeModal();
				// Update URL to reflect imported state
				await goto(`${window.location.pathname}${hash}`, { replaceState: true, noScroll: true });
			} else {
				importError = 'Failed to import data. The URL may be corrupted or invalid.';
			}
		} catch (error) {
			console.error('Import failed:', error);
			importError = 'Failed to import data. Please check the URL and try again.';
		} finally {
			isImporting = false;
		}
	}

	function closeModal() {
		showModal = false;
		shareUrl = '';
		importUrl = '';
		importError = '';
	}

	// Generate URL when modal opens
	$effect(() => {
		if (showModal && !shareUrl) {
			generateShareUrl();
		}
	});
</script>

<!-- Share Modal -->
{#if showModal}
	<div
		class="bg-opacity-50 fixed inset-0 z-50 flex items-center justify-center bg-black print:hidden"
	>
		<div class="w-full max-w-2xl rounded-lg bg-[var(--color-bg-secondary)] p-6 shadow-xl">
			<div class="mb-4 flex items-center justify-between">
				<h3 class="text-xl font-semibold text-[var(--color-text)]">Share Lineup</h3>
				<button
					class="text-[var(--color-text-muted)] hover:text-[var(--color-text)]"
					onclick={closeModal}
					aria-label="Close share modal"
				>
					<svg class="h-6 w-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
						<path
							stroke-linecap="round"
							stroke-linejoin="round"
							stroke-width="2"
							d="M6 18L18 6M6 6l12 12"
						/>
					</svg>
				</button>
			</div>

			<div class="space-y-4">
				<!-- Share URL Section -->
				<div>
					<h4 class="mb-2 text-lg font-medium text-[var(--color-text-light)]">Share Your Lineup</h4>
					<p class="mb-3 text-sm text-[var(--color-text-muted)]">
						Copy this URL to share your lineup with other coaches. The URL contains all your roster,
						player capabilities, and generated lineups.
					</p>

					{#if shareUrl}
						<div class="mb-3 rounded border bg-[var(--color-bg-accent)] p-3">
							<div class="mb-2 flex items-center justify-between">
								<span class="text-sm font-medium text-[var(--color-text-light)]">Share URL:</span>
								<span class="text-xs text-[var(--color-text-muted)]">{urlSize} bytes</span>
							</div>
							<div class="mb-2 rounded bg-white p-2 text-sm break-all text-[var(--color-text)]">
								{shareUrl}
							</div>
							<button
								class="w-full rounded bg-[var(--color-primary)] px-4 py-2 text-white transition-colors hover:bg-[var(--color-primary-dark)]"
								onclick={copyShareUrl}
							>
								Copy URL to Clipboard
							</button>
						</div>
					{/if}
				</div>

				<!-- Import URL Section -->
				<div class="border-t border-[var(--color-border)] pt-4">
					<h4 class="mb-2 text-lg font-medium text-[var(--color-text-light)]">Import Lineup</h4>
					<p class="mb-3 text-sm text-[var(--color-text-muted)]">
						Paste a share URL from another coach to load their lineup data.
					</p>

					<div class="space-y-3">
						<input
							type="url"
							bind:value={importUrl}
							placeholder="Paste share URL here..."
							class="w-full rounded border border-[var(--color-border)] bg-[var(--color-bg-secondary)] p-3 text-[var(--color-text)] focus:border-[var(--color-primary)] focus:outline-none"
						/>

						{#if importError}
							<div
								class="bg-opacity-10 rounded border border-[var(--color-error)] bg-[var(--color-error)] p-3 text-sm text-[var(--color-error)]"
							>
								{importError}
							</div>
						{/if}

						<button
							class="w-full rounded bg-[var(--color-secondary)] px-4 py-2 text-white transition-colors hover:bg-[var(--color-secondary-dark)] disabled:opacity-50"
							onclick={importFromUrl}
							disabled={isImporting || !importUrl.trim()}
						>
							{#if isImporting}
								<span class="flex items-center justify-center gap-2">
									<svg class="h-4 w-4 animate-spin" fill="none" viewBox="0 0 24 24">
										<circle
											class="opacity-25"
											cx="12"
											cy="12"
											r="10"
											stroke="currentColor"
											stroke-width="4"
										></circle>
										<path
											class="opacity-75"
											fill="currentColor"
											d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
										></path>
									</svg>
									Importing...
								</span>
							{:else}
								Import Lineup
							{/if}
						</button>
					</div>
				</div>

				<!-- Info Section -->
				<div class="rounded bg-[var(--color-bg-accent)] p-3 text-sm text-[var(--color-text-muted)]">
					<p class="mb-1 font-medium text-[var(--color-text-light)]">How it works:</p>
					<ul class="space-y-1 text-xs">
						<li>• Your lineup data is compressed and encoded into the URL</li>
						<li>• No data is sent to any server - everything is client-side</li>
						<li>• URLs include checksums to detect corruption</li>
						<li>• Data is automatically saved to the URL as you make changes</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
{/if}
